FROM public.ecr.aws/lambda/python:3.11

# Copio el archivo con las librerias a instalar
COPY src_production/changes_sp500/requirements.txt .

# Instalo las librerias
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copio el codigo de interes
COPY src_production/changes_sp500/changes_sp500.py ${LAMBDA_TASK_ROOT}

# Nombre del codigo 
CMD [ "changes_sp500.handler" ]
