FROM public.ecr.aws/lambda/python:3.11

# 1. Copiamos los requerimientos
COPY src/composition_sp500/requirements.txt .

# 2. Instalamos usando --target (como en tu ejemplo exitoso)
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# 3. Copiamos el código
COPY src/composition_sp500/composition_sp500.py ${LAMBDA_TASK_ROOT}

# 4. Ajustamos el CMD al nombre de tu archivo
CMD [ "composition_sp500.handler" ]

