FROM public.ecr.aws/lambda/python:3.11

# Copio el archivo con las librerias a instalar
COPY src_production/prices_and_volumes/requirements.txt .

# Instalo las librerias
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copio el archivo con el codigo python
COPY src_production/prices_and_volumes/prices_and_volumes.py ${LAMBDA_TASK_ROOT}

# Nombre de dicho archivo del codigo
CMD [ "prices_and_volumes.handler" ]