FROM public.ecr.aws/lambda/python:3.11

# Copio el archivo con las librerias a instalar
COPY src_production/trading_system/requirements.txt .

# Instalo las librerias
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copio el archivo con el codigo python
COPY src_production/trading_system/trading_system.py ${LAMBDA_TASK_ROOT}

# Nombre de dicho archivo con el codigo
CMD [ "trading_system.handler" ]