FROM public.ecr.aws/lambda/python:3.11

COPY src/update_wikipedia_keys/requirements.txt .
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY src/update_wikipedia_keys/update_wikipedia_keys.py ${LAMBDA_TASK_ROOT}

CMD [ "update_wikipedia_keys.handler" ]
