FROM public.ecr.aws/lambda/python:3.11

# Copio el archivo de requirements
COPY src_training/sp500_period_composition/requirements.txt .

# Instalo las librerias necesarias
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copio el codigo
COPY src_training/sp500_period_composition/sp500_period_composition.py ${LAMBDA_TASK_ROOT}

# Indico el codigo que debe ejecutar
CMD [ "sp500_period_composition.handler" ]
