FROM public.ecr.aws/lambda/python:3.11

# Copio el archivo con las librerias a instalar
COPY src_production/composition_sp500/requirements.txt .

# Instalo las librerias 
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copio el archivo del codigo python
COPY src_production/composition_sp500/composition_sp500.py ${LAMBDA_TASK_ROOT}

# Nombre de dicho codigo
CMD [ "composition_sp500.handler" ]
