FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copiamos usando las rutas relativas desde la raíz del proyecto
COPY src/balance_graph/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/balance_graph/balance_graph.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "balance_graph.py", "--server.port=8501", "--server.address=0.0.0.0"]