# # EJECUTA INFERENCIA
# name: Model Inference Pipeline


# on:
#   push:
#     branches: [ main ]  # Se ejecuta cada vez que subes cambios a main
#   workflow_dispatch:    # Permite ejecutarlo manualmente desde la pestaña Actions

# jobs:
#   build-and-run:
#     runs-on: ubuntu-latest
    
#     # Definimos variables de entorno para las APIs
#     env:
#       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' # Versión estable para torch y spacy

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pandas boto3 torch scikit-learn transformers \
#                       ctransformers sentencepiece rapidfuzz groq \
#                       sentence-transformers spacy[transformers]
#           # Descarga del modelo de Spacy (esto puede tardar un par de minutos)
#           python -m spacy download en_core_web_trf

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1 # Asegúrate de que coincida con tu región de Dynamo/S3

#       - name: Run Inference Script
#         run: python src/model_inference/model_inference.py



# name: Ejecucion Diaria Precios

name: Ejecutar Simulador Diario

on:
  # 1. Ejecución automática por tiempo (Lunes a Viernes a las 21:00 UTC / 23:00 España)
  schedule:
    - cron: '0 21 * * 1-5'
  
  # 2. Permite que tú puedas ejecutarlo haciendo clic en un botón cuando quieras probar
  workflow_dispatch: 

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas boto3 requests pytz

      - name: Run Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: python src/prices_and_volumes/prices_and_volumes_github.py




# Esto es para las imagenes de datos
# name: Build and Push Multiple Images to ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         include:
#           - repository: update_changes_sp500
#             dockerfile: dockerfiles/changes_sp500/dockerfile

#           - repository: update_composition_sp500
#             dockerfile: dockerfiles/composition_sp500/dockerfile

#           - repository: update_morningstar
#             dockerfile: dockerfiles/morningstar/dockerfile

#           - repository: update_wikipedia_keys
#             dockerfile: dockerfiles/wikipedia_keys/dockerfile

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ matrix.repository }}
#         run: |
#           docker build \
#             -t $ECR_REGISTRY/$ECR_REPOSITORY:imagen_oficial \
#             -f ${{ matrix.dockerfile }} .

#       - name: Push Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ matrix.repository }}
#         run: |
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:imagen_oficial


# Esto es para SISTEMA DE TRADING
# name: Build and Push Multiple Images to ECR

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         include:
#           - repository: update_trading_system
#             dockerfile: dockerfiles/trading_system/dockerfile


#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ matrix.repository }}
#         run: |
#           docker build \
#             -t $ECR_REGISTRY/$ECR_REPOSITORY:latest_7 \
#             -f ${{ matrix.dockerfile }} .

#       - name: Push Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ matrix.repository }}
#         run: |
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest_7


# DESPLIEGO EL APPRUNNER

# name: Deploy Balance Graph to ECR

# on:
#   push:
#     branches: [ main ] # Cambia por tu rama principal si es master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v2
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Build, Tag, and Push Image to ECR
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         ECR_REPOSITORY: update_balance_graph # Nombre de tu repositorio ECR
#         IMAGE_TAG: latest
#       run: |
#         # Usamos -f para indicar dónde está el Dockerfile, pero el contexto es la raíz (.)
#         docker build -f dockerfiles/balance_graph/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



# DESPLEGAR GRAFICA

# name: Deploy Balance Graph to ECR

# Se desactiva el push automático y se cambia a ejecución manual
# on:
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Code
#       run: echo "Workflow desactivado temporalmente"  # <--- CORREGIDO AQUÍ
