name: Ejecucion Diaria Precios

on:
  schedule:
    - cron: '00 17 * * *' 
  workflow_dispatch: # Botón para ejecutar a mano

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r src/close_prices/requirements.txt

      - name: Run Script
        env:
          # Configura estos secretos en Settings > Secrets del repo
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: python src/close_prices/close_prices.py
