name: Ejecutar Composicion S&P 500

on:
  # Se ejecuta automáticamente al subir cambios a la rama main
  push:
    branches:
      - main
  
  # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub
  workflow_dispatch: 
  
jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas python-dateutil boto3

      - name: Run Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          # Añade aquí tus otras variables de entorno (como API_KEY) si tu script las necesita
        run: python src_training/sp500_period_composition/sp500_period_composition.py
