# # EJECUTA INFERENCIA

name: Model Inference Pipeline

on:
  # 1. Ejecución automática por tiempo (Lunes a Viernes a las 21:00 UTC / 23:00 España)
  schedule:
    - cron: '30 21 * * 1-5'
  
  # 2. Permite ejecutarlo manualmente desde la pestaña Actions para hacer pruebas
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    # Definimos variables de entorno para las APIs
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Versión estable para torch y spacy

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas boto3 torch scikit-learn transformers \
                      ctransformers sentencepiece rapidfuzz groq \
                      sentence-transformers spacy[transformers]
          # Descarga del modelo de Spacy (esto puede tardar un par de minutos)
          python -m spacy download en_core_web_trf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Asegúrate de que coincida con tu región de Dynamo/S3

      - name: Run Inference Script
        run: python src/model_inference/model_inference.py