name: Deploy Multiple Lambdas to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Ajusta a tu región

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # # --- PROCESO 1: CHANGES SP500 (SCRAPER) ---
      # - name: Build and Push Changes Scraper
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: update_changes_sp500 # <--- Tu repo ECR para el scraper
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f dockerfiles/changes_sp500/Dockerfile .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # # --- PROCESO 2: COMPOSITION SP500 (HISTORIC) ---
      # - name: Build and Push Composition Historic
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: update_composition_sp500 # <--- Tu repo ECR para el histórico
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f dockerfiles/composition_sp500/Dockerfile .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # # --- PROCESO 3: MORNINGSTAR UPDATER ---
      # - name: Build and Push Morningstar
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: update_morningstar
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f dockerfiles/morningstar/Dockerfile .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # --- PROCESO 4: WIKIPEDIA UPDATER ---
      - name: Build and Push Wikipedia
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: update_wikipedia_keys
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f dockerfiles/_keys/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

     